const searchDummyData = [
  {
    login: 'Daegu',
    id: 34995541,
    node_id: 'MDQ6VXNlcjM0OTk1NTQx',
    avatar_url: 'https://avatars.githubusercontent.com/u/34995541?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Daegu',
    html_url: 'https://github.com/Daegu',
    followers_url: 'https://api.github.com/users/Daegu/followers',
    following_url: 'https://api.github.com/users/Daegu/following{/other_user}',
    gists_url: 'https://api.github.com/users/Daegu/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Daegu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Daegu/subscriptions',
    organizations_url: 'https://api.github.com/users/Daegu/orgs',
    repos_url: 'https://api.github.com/users/Daegu/repos',
    events_url: 'https://api.github.com/users/Daegu/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Daegu/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguIT-MinSuKim',
    id: 24215110,
    node_id: 'MDQ6VXNlcjI0MjE1MTEw',
    avatar_url: 'https://avatars.githubusercontent.com/u/24215110?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguIT-MinSuKim',
    html_url: 'https://github.com/DaeguIT-MinSuKim',
    followers_url: 'https://api.github.com/users/DaeguIT-MinSuKim/followers',
    following_url:
      'https://api.github.com/users/DaeguIT-MinSuKim/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguIT-MinSuKim/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguIT-MinSuKim/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DaeguIT-MinSuKim/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguIT-MinSuKim/orgs',
    repos_url: 'https://api.github.com/users/DaeguIT-MinSuKim/repos',
    events_url:
      'https://api.github.com/users/DaeguIT-MinSuKim/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguIT-MinSuKim/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguDude',
    id: 35420073,
    node_id: 'MDQ6VXNlcjM1NDIwMDcz',
    avatar_url: 'https://avatars.githubusercontent.com/u/35420073?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguDude',
    html_url: 'https://github.com/DaeguDude',
    followers_url: 'https://api.github.com/users/DaeguDude/followers',
    following_url:
      'https://api.github.com/users/DaeguDude/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguDude/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguDude/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DaeguDude/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguDude/orgs',
    repos_url: 'https://api.github.com/users/DaeguDude/repos',
    events_url: 'https://api.github.com/users/DaeguDude/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguDude/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'ryokousuru',
    id: 51663869,
    node_id: 'MDQ6VXNlcjUxNjYzODY5',
    avatar_url: 'https://avatars.githubusercontent.com/u/51663869?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ryokousuru',
    html_url: 'https://github.com/ryokousuru',
    followers_url: 'https://api.github.com/users/ryokousuru/followers',
    following_url:
      'https://api.github.com/users/ryokousuru/following{/other_user}',
    gists_url: 'https://api.github.com/users/ryokousuru/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/ryokousuru/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ryokousuru/subscriptions',
    organizations_url: 'https://api.github.com/users/ryokousuru/orgs',
    repos_url: 'https://api.github.com/users/ryokousuru/repos',
    events_url: 'https://api.github.com/users/ryokousuru/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ryokousuru/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegun',
    id: 827857,
    node_id: 'MDQ6VXNlcjgyNzg1Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/827857?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegun',
    html_url: 'https://github.com/daegun',
    followers_url: 'https://api.github.com/users/daegun/followers',
    following_url: 'https://api.github.com/users/daegun/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegun/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/daegun/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daegun/subscriptions',
    organizations_url: 'https://api.github.com/users/daegun/orgs',
    repos_url: 'https://api.github.com/users/daegun/repos',
    events_url: 'https://api.github.com/users/daegun/events{/privacy}',
    received_events_url: 'https://api.github.com/users/daegun/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'nabilera1',
    id: 8213301,
    node_id: 'MDQ6VXNlcjgyMTMzMDE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/8213301?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/nabilera1',
    html_url: 'https://github.com/nabilera1',
    followers_url: 'https://api.github.com/users/nabilera1/followers',
    following_url:
      'https://api.github.com/users/nabilera1/following{/other_user}',
    gists_url: 'https://api.github.com/users/nabilera1/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/nabilera1/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/nabilera1/subscriptions',
    organizations_url: 'https://api.github.com/users/nabilera1/orgs',
    repos_url: 'https://api.github.com/users/nabilera1/repos',
    events_url: 'https://api.github.com/users/nabilera1/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/nabilera1/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'Dianeha',
    id: 49717518,
    node_id: 'MDQ6VXNlcjQ5NzE3NTE4',
    avatar_url: 'https://avatars.githubusercontent.com/u/49717518?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Dianeha',
    html_url: 'https://github.com/Dianeha',
    followers_url: 'https://api.github.com/users/Dianeha/followers',
    following_url:
      'https://api.github.com/users/Dianeha/following{/other_user}',
    gists_url: 'https://api.github.com/users/Dianeha/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Dianeha/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Dianeha/subscriptions',
    organizations_url: 'https://api.github.com/users/Dianeha/orgs',
    repos_url: 'https://api.github.com/users/Dianeha/repos',
    events_url: 'https://api.github.com/users/Dianeha/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Dianeha/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegukdo',
    id: 38026518,
    node_id: 'MDQ6VXNlcjM4MDI2NTE4',
    avatar_url: 'https://avatars.githubusercontent.com/u/38026518?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegukdo',
    html_url: 'https://github.com/daegukdo',
    followers_url: 'https://api.github.com/users/daegukdo/followers',
    following_url:
      'https://api.github.com/users/daegukdo/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegukdo/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/daegukdo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daegukdo/subscriptions',
    organizations_url: 'https://api.github.com/users/daegukdo/orgs',
    repos_url: 'https://api.github.com/users/daegukdo/repos',
    events_url: 'https://api.github.com/users/daegukdo/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daegukdo/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'esusige3',
    id: 32057641,
    node_id: 'MDQ6VXNlcjMyMDU3NjQx',
    avatar_url: 'https://avatars.githubusercontent.com/u/32057641?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/esusige3',
    html_url: 'https://github.com/esusige3',
    followers_url: 'https://api.github.com/users/esusige3/followers',
    following_url:
      'https://api.github.com/users/esusige3/following{/other_user}',
    gists_url: 'https://api.github.com/users/esusige3/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/esusige3/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/esusige3/subscriptions',
    organizations_url: 'https://api.github.com/users/esusige3/orgs',
    repos_url: 'https://api.github.com/users/esusige3/repos',
    events_url: 'https://api.github.com/users/esusige3/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/esusige3/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'dayaelee',
    id: 57593704,
    node_id: 'MDQ6VXNlcjU3NTkzNzA0',
    avatar_url: 'https://avatars.githubusercontent.com/u/57593704?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/dayaelee',
    html_url: 'https://github.com/dayaelee',
    followers_url: 'https://api.github.com/users/dayaelee/followers',
    following_url:
      'https://api.github.com/users/dayaelee/following{/other_user}',
    gists_url: 'https://api.github.com/users/dayaelee/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/dayaelee/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/dayaelee/subscriptions',
    organizations_url: 'https://api.github.com/users/dayaelee/orgs',
    repos_url: 'https://api.github.com/users/dayaelee/repos',
    events_url: 'https://api.github.com/users/dayaelee/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/dayaelee/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DAEGU-Smart-City-Research',
    id: 71958648,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjcxOTU4NjQ4',
    avatar_url: 'https://avatars.githubusercontent.com/u/71958648?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DAEGU-Smart-City-Research',
    html_url: 'https://github.com/DAEGU-Smart-City-Research',
    followers_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/followers',
    following_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/following{/other_user}',
    gists_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/subscriptions',
    organizations_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/orgs',
    repos_url: 'https://api.github.com/users/DAEGU-Smart-City-Research/repos',
    events_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DAEGU-Smart-City-Research/received_events',
    type: 'Organization',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguKIng',
    id: 60918322,
    node_id: 'MDQ6VXNlcjYwOTE4MzIy',
    avatar_url: 'https://avatars.githubusercontent.com/u/60918322?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguKIng',
    html_url: 'https://github.com/DaeguKIng',
    followers_url: 'https://api.github.com/users/DaeguKIng/followers',
    following_url:
      'https://api.github.com/users/DaeguKIng/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguKIng/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguKIng/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DaeguKIng/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguKIng/orgs',
    repos_url: 'https://api.github.com/users/DaeguKIng/repos',
    events_url: 'https://api.github.com/users/DaeguKIng/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguKIng/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegunkor',
    id: 19787826,
    node_id: 'MDQ6VXNlcjE5Nzg3ODI2',
    avatar_url: 'https://avatars.githubusercontent.com/u/19787826?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegunkor',
    html_url: 'https://github.com/daegunkor',
    followers_url: 'https://api.github.com/users/daegunkor/followers',
    following_url:
      'https://api.github.com/users/daegunkor/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegunkor/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/daegunkor/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daegunkor/subscriptions',
    organizations_url: 'https://api.github.com/users/daegunkor/orgs',
    repos_url: 'https://api.github.com/users/daegunkor/repos',
    events_url: 'https://api.github.com/users/daegunkor/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daegunkor/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'quntnim',
    id: 80930697,
    node_id: 'MDQ6VXNlcjgwOTMwNjk3',
    avatar_url: 'https://avatars.githubusercontent.com/u/80930697?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/quntnim',
    html_url: 'https://github.com/quntnim',
    followers_url: 'https://api.github.com/users/quntnim/followers',
    following_url:
      'https://api.github.com/users/quntnim/following{/other_user}',
    gists_url: 'https://api.github.com/users/quntnim/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/quntnim/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/quntnim/subscriptions',
    organizations_url: 'https://api.github.com/users/quntnim/orgs',
    repos_url: 'https://api.github.com/users/quntnim/repos',
    events_url: 'https://api.github.com/users/quntnim/events{/privacy}',
    received_events_url: 'https://api.github.com/users/quntnim/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguChickenSystem',
    id: 39309620,
    node_id: 'MDQ6VXNlcjM5MzA5NjIw',
    avatar_url: 'https://avatars.githubusercontent.com/u/39309620?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguChickenSystem',
    html_url: 'https://github.com/DaeguChickenSystem',
    followers_url: 'https://api.github.com/users/DaeguChickenSystem/followers',
    following_url:
      'https://api.github.com/users/DaeguChickenSystem/following{/other_user}',
    gists_url:
      'https://api.github.com/users/DaeguChickenSystem/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguChickenSystem/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DaeguChickenSystem/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguChickenSystem/orgs',
    repos_url: 'https://api.github.com/users/DaeguChickenSystem/repos',
    events_url:
      'https://api.github.com/users/DaeguChickenSystem/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguChickenSystem/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguBlues',
    id: 18647154,
    node_id: 'MDQ6VXNlcjE4NjQ3MTU0',
    avatar_url: 'https://avatars.githubusercontent.com/u/18647154?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguBlues',
    html_url: 'https://github.com/DaeguBlues',
    followers_url: 'https://api.github.com/users/DaeguBlues/followers',
    following_url:
      'https://api.github.com/users/DaeguBlues/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguBlues/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguBlues/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DaeguBlues/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguBlues/orgs',
    repos_url: 'https://api.github.com/users/DaeguBlues/repos',
    events_url: 'https://api.github.com/users/DaeguBlues/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguBlues/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegunmin',
    id: 24703901,
    node_id: 'MDQ6VXNlcjI0NzAzOTAx',
    avatar_url: 'https://avatars.githubusercontent.com/u/24703901?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegunmin',
    html_url: 'https://github.com/daegunmin',
    followers_url: 'https://api.github.com/users/daegunmin/followers',
    following_url:
      'https://api.github.com/users/daegunmin/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegunmin/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/daegunmin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daegunmin/subscriptions',
    organizations_url: 'https://api.github.com/users/daegunmin/orgs',
    repos_url: 'https://api.github.com/users/daegunmin/repos',
    events_url: 'https://api.github.com/users/daegunmin/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daegunmin/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daeguk54',
    id: 10717448,
    node_id: 'MDQ6VXNlcjEwNzE3NDQ4',
    avatar_url: 'https://avatars.githubusercontent.com/u/10717448?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daeguk54',
    html_url: 'https://github.com/daeguk54',
    followers_url: 'https://api.github.com/users/daeguk54/followers',
    following_url:
      'https://api.github.com/users/daeguk54/following{/other_user}',
    gists_url: 'https://api.github.com/users/daeguk54/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/daeguk54/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daeguk54/subscriptions',
    organizations_url: 'https://api.github.com/users/daeguk54/orgs',
    repos_url: 'https://api.github.com/users/daeguk54/repos',
    events_url: 'https://api.github.com/users/daeguk54/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daeguk54/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegun83',
    id: 15179271,
    node_id: 'MDQ6VXNlcjE1MTc5Mjcx',
    avatar_url: 'https://avatars.githubusercontent.com/u/15179271?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegun83',
    html_url: 'https://github.com/daegun83',
    followers_url: 'https://api.github.com/users/daegun83/followers',
    following_url:
      'https://api.github.com/users/daegun83/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegun83/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/daegun83/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daegun83/subscriptions',
    organizations_url: 'https://api.github.com/users/daegun83/orgs',
    repos_url: 'https://api.github.com/users/daegun83/repos',
    events_url: 'https://api.github.com/users/daegun83/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daegun83/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daeguri',
    id: 5035740,
    node_id: 'MDQ6VXNlcjUwMzU3NDA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5035740?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daeguri',
    html_url: 'https://github.com/daeguri',
    followers_url: 'https://api.github.com/users/daeguri/followers',
    following_url:
      'https://api.github.com/users/daeguri/following{/other_user}',
    gists_url: 'https://api.github.com/users/daeguri/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/daeguri/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daeguri/subscriptions',
    organizations_url: 'https://api.github.com/users/daeguri/orgs',
    repos_url: 'https://api.github.com/users/daeguri/repos',
    events_url: 'https://api.github.com/users/daeguri/events{/privacy}',
    received_events_url: 'https://api.github.com/users/daeguri/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguDevGroup',
    id: 11812245,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjExODEyMjQ1',
    avatar_url: 'https://avatars.githubusercontent.com/u/11812245?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguDevGroup',
    html_url: 'https://github.com/DaeguDevGroup',
    followers_url: 'https://api.github.com/users/DaeguDevGroup/followers',
    following_url:
      'https://api.github.com/users/DaeguDevGroup/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguDevGroup/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguDevGroup/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DaeguDevGroup/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguDevGroup/orgs',
    repos_url: 'https://api.github.com/users/DaeguDevGroup/repos',
    events_url: 'https://api.github.com/users/DaeguDevGroup/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguDevGroup/received_events',
    type: 'Organization',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegunkis',
    id: 79190459,
    node_id: 'MDQ6VXNlcjc5MTkwNDU5',
    avatar_url: 'https://avatars.githubusercontent.com/u/79190459?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegunkis',
    html_url: 'https://github.com/daegunkis',
    followers_url: 'https://api.github.com/users/daegunkis/followers',
    following_url:
      'https://api.github.com/users/daegunkis/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegunkis/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/daegunkis/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daegunkis/subscriptions',
    organizations_url: 'https://api.github.com/users/daegunkis/orgs',
    repos_url: 'https://api.github.com/users/daegunkis/repos',
    events_url: 'https://api.github.com/users/daegunkis/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daegunkis/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DGSW-FLUT',
    id: 42262208,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjQyMjYyMjA4',
    avatar_url: 'https://avatars.githubusercontent.com/u/42262208?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DGSW-FLUT',
    html_url: 'https://github.com/DGSW-FLUT',
    followers_url: 'https://api.github.com/users/DGSW-FLUT/followers',
    following_url:
      'https://api.github.com/users/DGSW-FLUT/following{/other_user}',
    gists_url: 'https://api.github.com/users/DGSW-FLUT/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DGSW-FLUT/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/DGSW-FLUT/subscriptions',
    organizations_url: 'https://api.github.com/users/DGSW-FLUT/orgs',
    repos_url: 'https://api.github.com/users/DGSW-FLUT/repos',
    events_url: 'https://api.github.com/users/DGSW-FLUT/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DGSW-FLUT/received_events',
    type: 'Organization',
    site_admin: false,
    score: 1,
  },
  {
    login: 'EunChongJu',
    id: 17059831,
    node_id: 'MDQ6VXNlcjE3MDU5ODMx',
    avatar_url: 'https://avatars.githubusercontent.com/u/17059831?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/EunChongJu',
    html_url: 'https://github.com/EunChongJu',
    followers_url: 'https://api.github.com/users/EunChongJu/followers',
    following_url:
      'https://api.github.com/users/EunChongJu/following{/other_user}',
    gists_url: 'https://api.github.com/users/EunChongJu/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/EunChongJu/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/EunChongJu/subscriptions',
    organizations_url: 'https://api.github.com/users/EunChongJu/orgs',
    repos_url: 'https://api.github.com/users/EunChongJu/repos',
    events_url: 'https://api.github.com/users/EunChongJu/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/EunChongJu/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daeguk',
    id: 10446339,
    node_id: 'MDQ6VXNlcjEwNDQ2MzM5',
    avatar_url: 'https://avatars.githubusercontent.com/u/10446339?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daeguk',
    html_url: 'https://github.com/daeguk',
    followers_url: 'https://api.github.com/users/daeguk/followers',
    following_url: 'https://api.github.com/users/daeguk/following{/other_user}',
    gists_url: 'https://api.github.com/users/daeguk/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/daeguk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daeguk/subscriptions',
    organizations_url: 'https://api.github.com/users/daeguk/orgs',
    repos_url: 'https://api.github.com/users/daeguk/repos',
    events_url: 'https://api.github.com/users/daeguk/events{/privacy}',
    received_events_url: 'https://api.github.com/users/daeguk/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'chwhse',
    id: 26079892,
    node_id: 'MDQ6VXNlcjI2MDc5ODky',
    avatar_url: 'https://avatars.githubusercontent.com/u/26079892?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/chwhse',
    html_url: 'https://github.com/chwhse',
    followers_url: 'https://api.github.com/users/chwhse/followers',
    following_url: 'https://api.github.com/users/chwhse/following{/other_user}',
    gists_url: 'https://api.github.com/users/chwhse/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/chwhse/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/chwhse/subscriptions',
    organizations_url: 'https://api.github.com/users/chwhse/orgs',
    repos_url: 'https://api.github.com/users/chwhse/repos',
    events_url: 'https://api.github.com/users/chwhse/events{/privacy}',
    received_events_url: 'https://api.github.com/users/chwhse/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'Daeguhyuk',
    id: 59333621,
    node_id: 'MDQ6VXNlcjU5MzMzNjIx',
    avatar_url: 'https://avatars.githubusercontent.com/u/59333621?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Daeguhyuk',
    html_url: 'https://github.com/Daeguhyuk',
    followers_url: 'https://api.github.com/users/Daeguhyuk/followers',
    following_url:
      'https://api.github.com/users/Daeguhyuk/following{/other_user}',
    gists_url: 'https://api.github.com/users/Daeguhyuk/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/Daeguhyuk/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Daeguhyuk/subscriptions',
    organizations_url: 'https://api.github.com/users/Daeguhyuk/orgs',
    repos_url: 'https://api.github.com/users/Daeguhyuk/repos',
    events_url: 'https://api.github.com/users/Daeguhyuk/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/Daeguhyuk/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguBankProject',
    id: 44189249,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjQ0MTg5MjQ5',
    avatar_url: 'https://avatars.githubusercontent.com/u/44189249?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguBankProject',
    html_url: 'https://github.com/DaeguBankProject',
    followers_url: 'https://api.github.com/users/DaeguBankProject/followers',
    following_url:
      'https://api.github.com/users/DaeguBankProject/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguBankProject/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguBankProject/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DaeguBankProject/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguBankProject/orgs',
    repos_url: 'https://api.github.com/users/DaeguBankProject/repos',
    events_url:
      'https://api.github.com/users/DaeguBankProject/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguBankProject/received_events',
    type: 'Organization',
    site_admin: false,
    score: 1,
  },
  {
    login: 'DaeguDesignStudy',
    id: 59554177,
    node_id: 'MDEyOk9yZ2FuaXphdGlvbjU5NTU0MTc3',
    avatar_url: 'https://avatars.githubusercontent.com/u/59554177?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/DaeguDesignStudy',
    html_url: 'https://github.com/DaeguDesignStudy',
    followers_url: 'https://api.github.com/users/DaeguDesignStudy/followers',
    following_url:
      'https://api.github.com/users/DaeguDesignStudy/following{/other_user}',
    gists_url: 'https://api.github.com/users/DaeguDesignStudy/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/DaeguDesignStudy/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/DaeguDesignStudy/subscriptions',
    organizations_url: 'https://api.github.com/users/DaeguDesignStudy/orgs',
    repos_url: 'https://api.github.com/users/DaeguDesignStudy/repos',
    events_url:
      'https://api.github.com/users/DaeguDesignStudy/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/DaeguDesignStudy/received_events',
    type: 'Organization',
    site_admin: false,
    score: 1,
  },
  {
    login: 'daegustagram',
    id: 68242322,
    node_id: 'MDQ6VXNlcjY4MjQyMzIy',
    avatar_url: 'https://avatars.githubusercontent.com/u/68242322?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daegustagram',
    html_url: 'https://github.com/daegustagram',
    followers_url: 'https://api.github.com/users/daegustagram/followers',
    following_url:
      'https://api.github.com/users/daegustagram/following{/other_user}',
    gists_url: 'https://api.github.com/users/daegustagram/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/daegustagram/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/daegustagram/subscriptions',
    organizations_url: 'https://api.github.com/users/daegustagram/orgs',
    repos_url: 'https://api.github.com/users/daegustagram/repos',
    events_url: 'https://api.github.com/users/daegustagram/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daegustagram/received_events',
    type: 'User',
    site_admin: false,
    score: 1,
  },
];

export default searchDummyData;
